name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: iOS Build Action
      uses: yukiarrr/ios-build-action@v1.3.0

    - name: Run tests
      run: swift test -v
